<?php

declare(strict_types=1);

/**
 * System Translations (English)
 * 
 * System alerts, automated reports, and administrative notifications
 * 
 * @author ICTServe Localization Team
 * @created 2025-11-11
 */

return [
    // System Alerts
    'alerts' => [
        'title' => 'ICTServe System Alert',
        'severity' => [
            'critical' => 'Critical',
            'high' => 'High',
            'medium' => 'Medium',
            'low' => 'Low',
        ],
        'types' => [
            'overdue_tickets' => 'Overdue Tickets',
            'overdue_loans' => 'Overdue Loans',
            'approval_delays' => 'Pending Approvals',
            'low_asset_availability' => 'Low Asset Availability',
            'system_health' => 'System Health',
        ],
        'metrics' => [
            'overdue_tickets' => 'Overdue Tickets',
            'overdue_loans' => 'Overdue Loans',
            'pending_approvals' => 'Pending Approvals',
            'warning_threshold' => 'Warning Threshold',
            'time_threshold' => 'Time Threshold',
            'asset_availability' => 'Asset Availability',
            'minimum_threshold' => 'Minimum Threshold',
            'current_time' => 'Current Time',
            'health_score' => 'Health Score',
        ],
        'details' => [
            'title' => 'Detailed Information',
            'ticket_number' => 'Ticket No.',
            'application_number' => 'Application No.',
            'subject' => 'Subject',
            'applicant_name' => 'Applicant Name',
            'days_overdue' => 'Days Overdue',
            'pending_since' => 'Pending Since',
            'asset_name' => 'Asset Name',
            'current_availability' => 'Current Availability',
        ],
        'actions' => [
            'title' => 'Recommended Actions',
            'view_dashboard' => 'View Analytics Dashboard',
            'review_tickets' => 'Review Overdue Tickets',
            'review_approvals' => 'Review Pending Approvals',
            'check_assets' => 'Check Asset Inventory',
            'view_system_status' => 'View System Status',
        ],
        'footer' => [
            'generated_at' => 'Alert generated at',
            'automatic_notice' => 'This alert is automatically generated by ICTServe System',
        ],
    ],

    // Automated Reports
    'reports' => [
        'greeting' => 'Assalamualaikum and Greetings,',
        'title' => 'Automated System Report',
        'overall_health' => 'Overall System Health',
        'key_metrics' => 'Key Metrics',
        'metrics' => [
            'total_tickets' => 'Total Tickets',
            'resolution_rate' => 'Resolution Rate',
            'approval_rate' => 'Approval Rate',
            'loan_applications' => 'Loan Applications',
            'average_response_time' => 'Average Response Time',
            'asset_utilization' => 'Asset Utilization',
            'system_uptime' => 'System Uptime',
            'active_users' => 'Active Users',
        ],
        'details' => [
            'title' => 'Detailed Information',
            'report_info' => 'Report Information',
            'report_name' => 'Report Name',
            'module' => 'Module',
            'frequency' => 'Frequency',
            'description' => 'Description',
            'format' => 'Format',
            'generated_on' => 'Generated On',
        ],
        'issues' => [
            'title' => '⚠️ Issues Requiring Attention',
            'none' => 'No issues detected - System operating normally',
        ],
        'suggestions' => [
            'title' => '💡 Improvement Suggestions',
        ],
        'formats' => [
            'csv' => 'CSV Data - Raw data format',
            'excel' => 'Excel Data - For advanced analysis',
            'pdf' => 'PDF Report - Ready to print',
        ],
        'footer' => [
            'thank_you' => 'Thank you for using ICTServe.',
            'regards' => 'Best regards,',
            'team' => 'BPM MOTAC Team',
        ],
    ],

    // Export Notifications
    'export' => [
        'ready' => [
            'title' => 'Your Export is Ready',
            'greeting' => 'Hello',
            'intro' => 'Your requested data export has been completed and is ready for download.',
            'details' => 'Export Details',
            'export_type' => 'Export Type',
            'records_count' => 'Records Count',
            'file_size' => 'File Size',
            'format' => 'Format',
            'expires_at' => 'Link Expires At',
            'download_button' => 'Download Export',
            'download_instructions' => 'Click the button above to download your export file. The download link will expire after 24 hours.',
            'footer_note' => 'This is an automated notification from ICTServe Export System.',
        ],
    ],

    // Security Incidents
    'security' => [
        'incident' => [
            'title' => 'Security Incident Alert',
            'greeting' => 'Security Alert',
            'intro' => 'A security incident has been detected in the ICTServe system and requires immediate attention.',
            'details' => 'Incident Details',
            'incident_type' => 'Incident Type',
            'severity' => 'Severity',
            'detection_time' => 'Detection Time',
            'affected_area' => 'Affected Area',
            'description' => 'Description',
            'actions_taken' => 'Actions Taken',
            'recommended_actions' => 'Recommended Actions',
            'view_details' => 'View Full Details',
            'contact_support' => 'Contact Security Team',
            'footer_note' => 'This is a critical security notification. Please take immediate action.',
        ],
    ],

    // Welcome Email
    'welcome' => [
        'title' => 'Welcome to ICTServe',
        'greeting' => 'Welcome',
        'intro' => 'Your account has been successfully created in the ICTServe system.',
        'getting_started' => 'Getting Started',
        'features' => [
            'title' => 'Key Features',
            'asset_loans' => 'Request asset loans online',
            'helpdesk' => 'Submit and track helpdesk tickets',
            'reports' => 'Access system reports and analytics',
            'profile' => 'Manage your profile and preferences',
        ],
        'login_info' => 'Login Information',
        'username' => 'Username',
        'portal_url' => 'Portal URL',
        'support' => 'Need Help?',
        'support_text' => 'Contact our support team if you have any questions or need assistance.',
        'login_button' => 'Login to ICTServe',
    ],

    // Submission Claimed
    'submission_claimed' => [
        'title' => 'Your Submission Has Been Claimed',
        'greeting' => 'Dear',
        'intro' => 'Your guest submission has been claimed and you now have access to track its progress.',
        'submission_details' => 'Submission Details',
        'submission_number' => 'Submission Number',
        'claimed_at' => 'Claimed At',
        'next_steps' => 'Next Steps',
        'access_portal' => 'You can now access the portal to:',
        'features' => [
            'track_progress' => 'Track submission progress in real-time',
            'receive_updates' => 'Receive status updates via email',
            'view_history' => 'View complete submission history',
            'submit_new' => 'Submit additional requests',
        ],
        'access_button' => 'Access Your Portal',
        'footer_note' => 'Welcome to ICTServe! We\'re here to serve you better.',
    ],
];
