Alias /ictserve "C:/laragon/www/ictserve-031125/public"

<Directory "C:/laragon/www/ictserve-031125/public">
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Require all granted
</Directory>
