FROM node:20-alpine

WORKDIR /app

RUN npm install -g @modelcontextprotocol/server-sequential-thinking

ENV DISABLE_THOUGHT_LOGGING=false

ENTRYPOINT ["npx", "@modelcontextprotocol/server-sequential-thinking"]
