<?php

declare(strict_types=1);

/**
 * Fix IDE Helper Duplicate PDF Classes
 *
 * This script removes duplicate PDF class declarations from _ide_helper.php
 * that are generated by barryvdh/laravel-ide-helper when there are multiple
 * facade aliases for the same class.
 */
$ideHelperPath = __DIR__.'/../_ide_helper.php';

if (! file_exists($ideHelperPath)) {
    echo "IDE helper file not found: {$ideHelperPath}\n";
    exit(1);
}

$content = file_get_contents($ideHelperPath);

// Remove duplicate PDF facade alias (keep only 'Pdf', remove 'PDF')
$content = preg_replace(
    '/^\s*class PDF extends \\\\Barryvdh\\\\DomPDF\\\\Facade\\\\Pdf \{\}\s*$/m',
    '',
    $content
);

// Remove duplicate full Pdf class declaration in Barryvdh\DomPDF\Facade namespace
// This is more complex as we need to remove the entire duplicate class block
$lines = explode("\n", $content);
$inDuplicateClass = false;
$braceCount = 0;
$filteredLines = [];
$duplicateStart = false;

foreach ($lines as $lineNum => $line) {
    // Look for the start of duplicate class Pdf in Barryvdh\DomPDF\Facade namespace
    if (
        preg_match('/^\s*\/\*\*\s*$/', $line) &&
        isset($lines[$lineNum + 1]) &&
        strpos($lines[$lineNum + 1], '@method static BasePDF') !== false
    ) {

        // Check if this is the second occurrence by looking ahead
        $foundFirstClass = false;
        for ($i = 0; $i < $lineNum; $i++) {
            if (strpos($lines[$i], 'class Pdf {') !== false) {
                $foundFirstClass = true;
                break;
            }
        }

        if ($foundFirstClass) {
            $inDuplicateClass = true;
            $duplicateStart = true;

            continue; // Skip this line
        }
    }

    if ($inDuplicateClass) {
        // Count braces to find the end of the class
        if (strpos($line, 'class Pdf {') !== false) {
            $braceCount = 1;
        } elseif ($braceCount > 0) {
            $braceCount += substr_count($line, '{') - substr_count($line, '}');

            if ($braceCount <= 0) {
                $inDuplicateClass = false;
                $braceCount = 0;

                continue; // Skip the closing brace line
            }
        }

        continue; // Skip all lines in duplicate class
    }

    $filteredLines[] = $line;
}

$cleanContent = implode("\n", $filteredLines);

// Remove any extra blank lines that might have been created
$cleanContent = preg_replace('/\n{3,}/', "\n\n", $cleanContent);

file_put_contents($ideHelperPath, $cleanContent);

echo "Fixed duplicate PDF classes in _ide_helper.php\n";
