name: RTM Validation

on:
  push:
    branches: [ develop, main ]
    paths:
      - 'app/**'
      - 'tests/**'
      - 'docs/rtm/**'
  pull_request:
    branches: [ develop, main ]

jobs:
  validate-rtm:
    runs-on: ubuntu-latest
    name: Validate Requirements Traceability Matrix

    steps:
      - uses: actions/checkout@v4

      - name: Check RTM file exists
        run: |
          if [ ! -f "docs/rtm/requirements-traceability.csv" ]; then
            echo "❌ RTM file not found: docs/rtm/requirements-traceability.csv"
            exit 1
          fi
          echo "✅ RTM file exists"

          # Show RTM summary
          echo ""
          echo "RTM Contents:"
          head -20 docs/rtm/requirements-traceability.csv

      - name: Extract SRS IDs from code
        run: |
          echo "Scanning codebase for SRS references..."

          # Search for SRS ID references in code
          grep -r "SRS-\|FR-\|NFR-\|BR-\|API-\|SEC-\|LANG-" \
            app/ tests/ routes/ \
            --include="*.php" \
            --include="*.blade.php" \
            2>/dev/null | grep -oE "[A-Z]+-[0-9]+" | sort -u > /tmp/code_refs.txt || true

          # Extract SRS IDs from RTM
          tail -n +2 docs/rtm/requirements-traceability.csv | cut -d, -f1 | sort -u > /tmp/rtm_refs.txt

          echo "SRS IDs in code: $(wc -l < /tmp/code_refs.txt)"
          echo "SRS IDs in RTM: $(wc -l < /tmp/rtm_refs.txt)"

          # Find gaps (IDs in code but not in RTM)
          echo ""
          echo "Checking for RTM gaps..."
          if GAPS=$(comm -23 <(sort /tmp/code_refs.txt) <(sort /tmp/rtm_refs.txt)); then
            if [ -n "$GAPS" ]; then
              echo "⚠️  Warning: SRS references in code not found in RTM:"
              echo "$GAPS"
              # Don't fail - just warn (new SRS IDs may be in development)
            else
              echo "✅ All SRS references are in RTM"
            fi
          fi

      - name: Validate RTM CSV format
        run: |
          echo "Validating RTM CSV format..."

          # Check for required columns
          HEADER=$(head -1 docs/rtm/requirements-traceability.csv)
          EXPECTED_COLS="srs_id,module,requirement_description,business_ref,design_ref,code_ref,test_case,implementation_status,notes"

          if [ "$HEADER" != "$EXPECTED_COLS" ]; then
            echo "❌ RTM CSV header mismatch"
            echo "Expected: $EXPECTED_COLS"
            echo "Got: $HEADER"
            exit 1
          fi

          # Check row count
          ROW_COUNT=$(tail -n +2 docs/rtm/requirements-traceability.csv | wc -l)
          echo "✅ RTM CSV format valid ($ROW_COUNT requirement(s))"

      - name: Check for duplicate SRS IDs
        run: |
          echo "Checking for duplicate SRS IDs in RTM..."

          DUPLICATES=$(tail -n +2 docs/rtm/requirements-traceability.csv | cut -d, -f1 | sort | uniq -d)

          if [ -n "$DUPLICATES" ]; then
            echo "❌ Duplicate SRS IDs found:"
            echo "$DUPLICATES"
            exit 1
          else
            echo "✅ No duplicate SRS IDs"
          fi

      - name: Verify implementation status updates
        if: github.event_name == 'pull_request'
        run: |
          echo "Checking for RTM status updates in PR..."

          # Get changed RTM files
          git fetch origin $ github.base_ref 
          if ! git diff origin/$ github.base_ref  --name-only | grep -q "docs/rtm"; then
            echo "ℹ️  No RTM changes in this PR"
            exit 0
          fi

          # Check for implementation_status changes
          if git diff origin/$ github.base_ref  docs/rtm/ | grep -q "completed\|in-progress"; then
            echo "✅ RTM implementation status updated"
          else
            echo "⚠️  RTM not updated with implementation status"
          fi

      - name: Comment on PR
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment(
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **RTM Validation Failed**\n\n' +
                    'Ensure:\n' +
                    '- RTM file exists at `docs/rtm/requirements-traceability.csv`\n' +
                    '- All SRS references in code are in the RTM\n' +
                    '- CSV format is valid (required columns)\n' +
                    '- No duplicate SRS IDs\n\n' +
                    'See [RTM File](docs/rtm/requirements-traceability.csv) for details.'
        )

      - name: Comment success on PR
        if: github.event_name == 'pull_request' && success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment(
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ **RTM Validation Passed**\n\n' +
                    '- RTM file exists and is valid\n' +
                    '- CSV format correct\n' +
                    '- No duplicate SRS IDs\n' +
                    '- SRS references are properly tracked'
        )
